package generate

import (
	"fmt"
	"strings"

	"github.com/AlexanderYAPPO/go-papa-carlo/entity"
)

const (
	_doNotEditComment = "// Code generated by github.com/AlexanderYAPPO/go-papa-carlo. DO NOT EDIT.\n"
)

// Generate creates source code for builders based on the parsing result.
func Generate(target entity.Target) string {
	codeLines := []string{_doNotEditComment}
	result := target.ParsingResult
	if result.PackageName != "" {
		codeLines = append(codeLines, fmt.Sprintf("package %s", result.PackageName), "")
	}
	imports := append([]entity.Import{}, result.Imports...)
	if target.Import.Path != "" {
		imports = append(imports, target.Import)
	}
	if len(imports) > 0 {
		codeLines = append(codeLines, generateImports(imports)...)
	}
	steps := buildFieldGenerationSteps(target)
	if len(steps) > 0 && len(codeLines) > 0 {
		codeLines = append(codeLines, "")
	}
	for i := len(steps) - 1; i >= 0; i-- {
		step := steps[i]
		codeLines = append(codeLines, step.Generate()...)
	}

	return strings.Join(codeLines, "\n")
}

func generateImports(imports []entity.Import) []string {
	codeLines := []string{}
	codeLines = append(codeLines, "import (")
	for _, i := range imports {
		newLine := fmt.Sprintf("    \"%s\"", i.Path)
		if i.IsAlias {
			newLine = fmt.Sprintf("    %s \"%s\"", i.ReferenceName, i.Path)
		}
		codeLines = append(codeLines, newLine)
	}
	codeLines = append(codeLines, ")")
	return codeLines
}
